# Generated by Django 4.0.4 on 2022-04-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitrackInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks_field', models.TimeField()),
            ],
        ),
    ]
